### PR TITLE
Updates iOS product page with 12.0 info

### PR DESCRIPTION
**Pull request by jahorton**

### CODE REVIEW

**Comment by darcywong00** [comment]
For previous stable releases, we'd put the content on a staging-xx branch and only merge it after the official release is live.

help.keyman.com is allowed to have "future" content, but
keyman.com is a front-facing site for the stable version.

**Comment by jahorton** [comment]
OK.  Well, consider this ready in advance for the 'staging' branch, then.

**Comment by darcywong00** [comment]
How about editing this PR to merge into `staging-12.0` instead of `master`? Then we can pile onto that branch.

**Comment by jahorton** [comment]
Oh.  Didn't realize it already existed.

**Pull request merged**
