### PR TITLE
feat: keyboard authoring service directory

### PR DESCRIPTION
**Pull request by mcdurdin**
Relates to a discussion on a forum:

https://community.software.sil.org/t/keyman-keyboard-creator-directory/9408/5

Once we get a name or two, we'll publish.

Form responses at: https://docs.google.com/forms/d/1bb42Gs09z6iqJf_ub63o9tEoOS27Rx_7omPPzfH3Mk0/edit#responses

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by LornaSIL** [comment]
lgtm too

**Review by srl295 — APPROVED** [review]

**Comment by mcdurdin** [comment]
@srl295 do you want to be added as well before I merge?

**Comment by srl295** [comment]
> @srl295 do you want to be added as well before I merge?

Not now :)

**Pull request merged**
