### PR TITLE
fix: exclude /donate from broken link checker

### PR DESCRIPTION
**Pull request by mcdurdin**
/donate redirects to another site that gives a 403 forbidden response to bots, which breaks the link checker. So just exclude it.

Fixes: #488

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm assuming the CI link check passes

**Comment by mcdurdin** [comment]
Hmm, turns out that there are 4 references to broken-link-checker. I can understand 2 of them, and no obvious way to consolidate those, but not sure why we have the ones in composer.json as well, would recommend removing them?

**Comment by darcywong00** [comment]
> but not sure why we have the ones in composer.json as well, would recommend removing them?

Ah, I added the one in composer.json in #389 for feature parity with help.keyman.com

I suppose we can remove in a separate PR

**Comment by mcdurdin** [comment]
> Ah, I added the one in composer.json in #389 for feature parity with help.keyman.com

Hmm, so we should probably remove from all then. Let's keep composer.json minimal, remove all scripts, seeing as we do them in ci.yml now?

I see we never call `composer run test` either, which means we should probably add `vendor/bin/phpunit --testdox` to ci.yml and/or Dockerfile?

How do we run lint and phpunit tests locally?

**Comment by darcywong00** [comment]
> I see we never call `composer run test` either, which means we should probably add `vendor/bin/phpunit --testdox` to ci.yml and/or Dockerfile?
> 
> How do we run lint and phpunit tests locally?

Looks like a TODO 😞 
https://github.com/keymanapp/keyman.com/blob/03025d8d5f9843e1ddaca205de059aaa794cf115/build.sh#L31

**Comment by mcdurdin** [comment]
Okay, added #493 to track composer.json/test changes

**Pull request merged**
