### PR TITLE
refactor: combine startAfterPageLoad functions for Windows and Linux

### PR DESCRIPTION
**Pull request by ermshiperete**

### CODE REVIEW

**Comment by mcdurdin** [comment]
I'm not convinced I want to merge these two functions. I think it makes maintenance more tricky...

**Comment by ermshiperete** [comment]
> I'm not convinced I want to merge these two functions. I think it makes maintenance more tricky...

That's what you suggested in #135 :smile: . But I don't mind either way.

**Comment by mcdurdin** [comment]
> That's what you suggested in #135 😄 . But I don't mind either way.

Well, my bad huh. Looking at the merged code now it just raises red flags for maintenance. Really sorry about sending you on that wild goose chase!

**Comment by ermshiperete** [comment]
> > That's what you suggested in #135 smile . But I don't mind either way.
> 
> Well, my bad huh. Looking at the merged code now it just raises red flags for maintenance. Really sorry about sending you on that wild goose chase!

no problem

**Pull request closed without merging**
